export const APP_URL = process.env.APP_URL ?? 'http://localhost:4321'
export const AI_PROVIDER = process.env.AI_PROVIDER ?? 'google'
export const AI_API_KEY = process.env.AI_API_KEY ?? 'test-ai-key'
export const AI_MODEL = process.env.AI_MODEL ?? 'gemini-2.5-flash'
export const AI_BASE_URL = process.env.AI_BASE_URL
export const DB_PROVIDER = process.env.DB_PROVIDER
export const DATABASE_URL = process.env.DATABASE_URL
export const SMTP_URL = process.env.SMTP_URL
export const SMTP_HOST = process.env.SMTP_HOST
export const SMTP_PORT = Number(process.env.SMTP_PORT ?? '587')
export const SMTP_USER = process.env.SMTP_USER
export const SMTP_PASS = process.env.SMTP_PASS
